<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<NoWarn>$(NoWarn);CS1591</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Agents.AI" />
		<PackageReference Include="ModelContextProtocol" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Banshee\Viv.Echo\Viv.Echo.csproj" />
		<ProjectReference Include="..\..\Banshee\Viv.Outbox\Viv.Outbox.csproj" />
		<ProjectReference Include="..\Viv.Elysia\Viv.Elysia.csproj" />
		<ProjectReference Include="..\Viv.Entity\Viv.Entity.csproj" />
		<ProjectReference Include="..\Viv.EventContracts\Viv.EventContracts.csproj" />
	</ItemGroup>

</Project>
