<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Autofac" />
		<PackageReference Include="Autofac.Extensions.DependencyInjection" />
		<PackageReference Include="Autofac.Extras.DynamicProxy" />
		<PackageReference Include="AWSSDK.S3" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Core" />
		<PackageReference Include="Newtonsoft.Json" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" />
		<PackageReference Include="Microsoft.Extensions.AI" />
		<PackageReference Include="Microsoft.Extensions.AI.OpenAI" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" />
		<PackageReference Include="Yarp.ReverseProxy" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Viv.Delusion\Viv.Delusion.csproj" />
	</ItemGroup>

</Project>
