using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Viv.Forge
{
    [Generator]
    public class GrpcClientGenerator : IIncrementalGenerator
    {
        private const string AttributeShortName = "GrpcClient";
        private const string AttributeFullName = "GrpcClientAttribute";
        private const string AttributeNamespace = "Viv.Echo.Grpc";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var clients = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: IsCandidateInterface,
                    transform: ExtractGrpcClient)
                .Where(x => x is not null)
                .Collect();

            context.RegisterSourceOutput(clients, GenerateRegistration);
        }

        private static bool IsCandidateInterface(SyntaxNode node, CancellationToken _)
        {
            return node is InterfaceDeclarationSyntax { AttributeLists.Count: > 0 };
        }

        private static GrpcClientInfo? ExtractGrpcClient(GeneratorSyntaxContext ctx, CancellationToken ct)
        {
            var iface = (InterfaceDeclarationSyntax)ctx.Node;
            var symbol = ctx.SemanticModel.GetDeclaredSymbol(iface, ct);
            if (symbol == null) return null;

            foreach (var attr in symbol.GetAttributes())
            {
                if (attr.AttributeClass is not { Name: AttributeShortName or AttributeFullName } attrClass)
                    continue;
                if (attrClass.ContainingNamespace?.ToDisplayString() != AttributeNamespace)
                    continue;

                var name = attr.ConstructorArguments.Length > 0
                    ? attr.ConstructorArguments[0].Value?.ToString()
                    : null;
                var address = attr.ConstructorArguments.Length > 1
                    ? attr.ConstructorArguments[1].Value?.ToString()
                    : null;

                if (string.IsNullOrEmpty(name) || string.IsNullOrEmpty(address))
                    continue;

                return new GrpcClientInfo(
                    symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                    name!,
                    address!);
            }

            return null;
        }

        private static void GenerateRegistration(SourceProductionContext ctx, ImmutableArray<GrpcClientInfo?> clients)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
            sb.AppendLine();
            sb.AppendLine("namespace Viv.Echo.Grpc");
            sb.AppendLine("{");
            sb.AppendLine("    public static class VivGrpcGeneratedExtensions");
            sb.AppendLine("    {");
            sb.AppendLine("        public static IServiceCollection AddVivGrpcClients(this IServiceCollection services)");
            sb.AppendLine("        {");

            if (!clients.IsDefaultOrEmpty)
            {
                foreach (var client in clients)
                {
                    if (client == null) continue;
                    sb.AppendLine($"            services.AddGrpcClient<{client.FullTypeName}>(o => o.Address = new System.Uri(\"{Escape(client.Address)}\"))");
                    sb.AppendLine("                .AddInterceptor<VivGrpcInterceptor>();");
                }
            }

            sb.AppendLine("            return services;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            ctx.AddSource("VivGrpcClients.g.cs", sb.ToString());
        }

        private static string Escape(string s) => s.Replace("\\", "\\\\").Replace("\"", "\\\"");

        private sealed class GrpcClientInfo
        {
            public GrpcClientInfo(string fullTypeName, string name, string address)
            {
                FullTypeName = fullTypeName;
                Name = name;
                Address = address;
            }
            public string FullTypeName { get; }
            public string Name { get; }
            public string Address { get; }
        }
    }
}
