using System;
using System.Collections.Generic;
using System.Text;

namespace Viv.Forge
{
    /// <summary>
    /// 源码生成辅助 —— 管理缩进、using 收集去重、<c>// &lt;auto-generated/&gt;</c> 头与代码块，
    /// 避免生成器子类手拼 <see cref="StringBuilder"/> 与缩进。
    /// </summary>
    public sealed class SourceBuilder
    {
        private readonly StringBuilder _sb = new();
        private readonly HashSet<string> _usings = new();
        private bool _autoGeneratedHeader;
        private int _indent;

        public SourceBuilder(bool includeAutoGeneratedHeader = true)
        {
            _autoGeneratedHeader = includeAutoGeneratedHeader;
        }

        /// <summary>当前正文长度（不含头/using），用于判断是否有产出。</summary>
        public int Length => _sb.Length;

        /// <summary>是否有正文内容（用于 AddSource 前判空）。</summary>
        public bool HasContent => _sb.Length > 0;

        /// <summary>追加 using（自动去重，输出时按字母排序）。</summary>
        public SourceBuilder Using(string ns)
        {
            if (!string.IsNullOrEmpty(ns)) _usings.Add(ns);
            return this;
        }

        /// <summary>写一行（自动缩进；空行传入 null/空串）。</summary>
        public SourceBuilder Line(string? text = null)
        {
            if (string.IsNullOrEmpty(text))
            {
                _sb.AppendLine();
                return this;
            }

            for (int i = 0; i < _indent; i++) _sb.Append("    ");
            _sb.AppendLine(text);
            return this;
        }

        /// <summary>追加原始文本（不换行、不缩进），用于拼方法体内部多段片段。</summary>
        public SourceBuilder Append(string text)
        {
            _sb.Append(text);
            return this;
        }

        /// <summary>追加一行原始文本（不缩进），用于粘贴子生成器已格式好的多行块。</summary>
        public SourceBuilder AppendLine(string text)
        {
            _sb.AppendLine(text);
            return this;
        }

        /// <summary>缩进 +1。</summary>
        public SourceBuilder Indent()
        {
            _indent++;
            return this;
        }

        /// <summary>缩进 -1。</summary>
        public SourceBuilder Outdent()
        {
            if (_indent > 0) _indent--;
            return this;
        }

        /// <summary>写 "xxx { " 并缩进。</summary>
        public SourceBuilder OpenBlock(string header)
        {
            Line(header + " {");
            _indent++;
            return this;
        }

        /// <summary>写 "}" 并退缩进。</summary>
        public SourceBuilder CloseBlock(string suffix = "")
        {
            _indent--;
            Line("}" + suffix);
            return this;
        }

        public override string ToString()
        {
            if (!HasContent) return string.Empty;

            var sb = new StringBuilder();
            if (_autoGeneratedHeader)
            {
                sb.AppendLine("// <auto-generated/>");
                sb.AppendLine();
            }

            if (_usings.Count > 0)
            {
                var sorted = new List<string>(_usings);
                sorted.Sort(StringComparer.Ordinal);
                foreach (var ns in sorted) sb.AppendLine($"using {ns};");
                sb.AppendLine();
            }

            sb.Append(_sb);
            return sb.ToString();
        }
    }
}
