using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading;
using Microsoft.CodeAnalysis;

namespace Viv.Forge
{
    /// <summary>
    /// 源生成器抽象基类 —— 封装完整的增量管线：
    /// 候选语法筛选 → 语义提取 → Collect → 合并程序集名 → 注册产出，并兜底捕获生成期异常为诊断。
    /// 子类只需实现四个成员：生成器名、语法候选谓词、语义提取、代码生成。
    /// 具体生成器类请标注 <c>[Generator]</c>（本基类抽象，不参与实例化）。
    /// </summary>
    /// <typeparam name="TInfo">从候选节点提取出的编译期信息；实现 <see cref="IEquatable{T}"/> 并配合
    /// <see cref="Comparer"/> 可开启增量缓存，未变化的候选不再触发重编译。</typeparam>
    public abstract class VivSourceGenerator<TInfo> : IIncrementalGenerator
        where TInfo : class
    {
        /// <summary>
        /// 生成器名：用于生成文件名（{GeneratorName}.g.cs）与诊断信息。
        /// </summary>
        protected abstract string GeneratorName { get; }

        /// <summary>
        /// 语法级快速过滤（不触碰语义模型），用于缩小候选范围。
        /// </summary>
        protected abstract bool IsCandidate(SyntaxNode node, CancellationToken ct);

        /// <summary>
        /// 语义提取：把候选节点转成 <typeparamref name="TInfo"/>；返回 null 表示跳过。
        /// </summary>
        protected abstract TInfo? Extract(GeneratorSyntaxContext ctx, CancellationToken ct);

        /// <summary>
        /// 生成逻辑：把所有提取结果写入 <see cref="VivGeneratorContext.Source"/>，产出源码。
        /// </summary>
        protected abstract void Generate(SourceProductionContext spc, ImmutableArray<TInfo> infos, VivGeneratorContext ctx);

        /// <summary>
        /// 增量比较器。当 <typeparamref name="TInfo"/> 实现 <see cref="IEquatable{T}"/> 时返回
        /// <see cref="EqualityComparer{T}.Default"/>，让未变化的候选不触发下游重编译；默认 null 表示不开启。
        /// </summary>
        protected virtual IEqualityComparer<TInfo>? Comparer => null;

        /// <summary>是否在文件头写 <c>// &lt;auto-generated/&gt;</c>（默认 true）。</summary>
        protected virtual bool IncludeAutoGeneratedHeader => true;

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // CreateSyntaxProvider 依 Extract 返回类型推断为 TInfo?；Where 不改变泛型参数，
            // 用两参数 Select 收敛回非空 TInfo（一参数 lambda 会歧义到单值 ValueProvider 的 Select 重载）
            var candidates = context.SyntaxProvider
                .CreateSyntaxProvider(IsCandidate, Extract)
                .Where(static x => x is not null)
                .Select(static (x, _) => x!);

            if (Comparer is not null)
            {
                candidates = candidates.WithComparer(Comparer);
            }

            var infos = candidates.Collect();
            var assemblyName = context.CompilationProvider
                .Select(static (c, _) => c.AssemblyName ?? "Unknown");

            context.RegisterSourceOutput(infos.Combine(assemblyName), RegisterOutput);
        }

        private void RegisterOutput(SourceProductionContext spc, (ImmutableArray<TInfo> Infos, string AssemblyName) data)
        {
            try
            {
                var ctx = new VivGeneratorContext(data.AssemblyName, new SourceBuilder(IncludeAutoGeneratedHeader));
                Generate(spc, data.Infos, ctx);
                if (ctx.Source.HasContent)
                {
                    spc.AddSource($"{GeneratorName}.g.cs", ctx.Source.ToString());
                }
            }
            catch (Exception ex)
            {
                // 生成期异常兜底为编译错误诊断，避免生成器崩溃拖垮整个编译
                spc.ReportDiagnostic(Diagnostic.Create(
                    GeneratorException,
                    Location.None,
                    GeneratorName,
                    ex.GetType().Name + ": " + ex.Message));
            }
        }

        // RS2008 要求 analyzer 项目带发布跟踪文件；框架内部兜底诊断不做版本化发布，抑制该告警
#pragma warning disable RS2008
        private static readonly DiagnosticDescriptor GeneratorException = new(
            id: "VIVGEN001",
            title: "源生成器内部异常",
            messageFormat: "生成器 {0} 抛出异常：{1}",
            category: "Viv.Forge",
            defaultSeverity: DiagnosticSeverity.Error,
            isEnabledByDefault: true);
#pragma warning restore RS2008
    }

    /// <summary>
    /// 生成期上下文 —— 携带目标程序集名（用于生成唯一命名/防跨程序集冲突）与源码构建器。
    /// </summary>
    public sealed class VivGeneratorContext
    {
        public VivGeneratorContext(string assemblyName, SourceBuilder source)
        {
            AssemblyName = assemblyName;
            Source = source;
        }

        /// <summary>正在编译的目标程序集名（无命名空间时用 "Unknown"）。</summary>
        public string AssemblyName { get; }

        /// <summary>源码构建器：缩进/using 去重/auto-generated 头统一由它管理。</summary>
        public SourceBuilder Source { get; }
    }
}
