<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="LocalMessage\" />
    <Folder Include="RedisPubSub\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="RabbitMQ.Client" Version="7.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Viv.Autofac\Viv.Autofac.csproj" />
    <ProjectReference Include="..\Viv.Contracts\Viv.Contracts.csproj" />
    <ProjectReference Include="..\Viv.Log\Viv.Log.csproj" />
    <ProjectReference Include="..\Viv.Vva\Viv.Vva.csproj" />
  </ItemGroup>

</Project>
