<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="WolverineFx" Version="6.25.3" />
    <PackageReference Include="WolverineFx.RabbitMQ" Version="6.25.3" />
    <PackageReference Include="WolverineFx.EntityFrameworkCore" Version="6.25.3" />
    <PackageReference Include="WolverineFx.RuntimeCompilation" Version="6.25.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Viv.Contracts\Viv.Contracts.csproj" />
    <ProjectReference Include="..\Viv.Log\Viv.Log.csproj" />
    <ProjectReference Include="..\Viv.Momo\Viv.Momo.csproj" />
  </ItemGroup>

</Project>
