<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<InterceptorsNamespaces>$(InterceptorsNamespaces);Microsoft.AspNetCore.OpenApi.Generated</InterceptorsNamespaces>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Viv.Aoi\Viv.Aoi.csproj" />
		<ProjectReference Include="..\Viv.Clockwork\Viv.Clockwork.csproj" />
		<ProjectReference Include="..\Viv.Contracts\Viv.Contracts.csproj" />
		<ProjectReference Include="..\Viv.Delusion\Viv.Delusion.csproj" />
		<ProjectReference Include="..\Viv.Momo\Viv.Momo.csproj" />
		<ProjectReference Include="..\Viv.Nana\Viv.Nana.csproj" />
		<ProjectReference Include="..\Viv.Redis\Viv.Redis.csproj" />
		<ProjectReference Include="..\Viv.Echo\Viv.Echo.csproj" />
		<ProjectReference Include="..\Viv.Sandrone\Viv.Sandrone.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <None Update="Htmls\app_404.html">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="Htmls\app_started.html">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	</ItemGroup>

</Project>
