<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  
  </PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" />
		<PackageReference Include="Scalar.AspNetCore" />
		<PackageReference Include="MiniExcel" />
		<PackageReference Include="SkiaSharp" />
		<PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" />
		<PackageReference Include="SkiaSharp.QrCode" />
	</ItemGroup>
	
  <ItemGroup>
    <ProjectReference Include="..\Viv.Aoi\Viv.Aoi.csproj" />
    <ProjectReference Include="..\Viv.Contracts\Viv.Contracts.csproj" />
    <ProjectReference Include="..\Viv.Delusion\Viv.Delusion.csproj" />
    <ProjectReference Include="..\Viv.Echo\Viv.Echo.csproj" />
    <ProjectReference Include="..\Viv.Log\Viv.Log.csproj" />
  </ItemGroup>

</Project>
