<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
	  <PackageReference Include="Serilog.Sinks.Seq" />
	  <PackageReference Include="Serilog" />
	  <PackageReference Include="Serilog.AspNetCore" />
	  <PackageReference Include="Serilog.Sinks.Console" />
	  <PackageReference Include="Serilog.Sinks.File" />
  </ItemGroup>

  <ItemGroup>
	  <ProjectReference Include="..\Viv.Aoi\Viv.Aoi.csproj" />
	  <ProjectReference Include="..\Viv.Contracts\Viv.Contracts.csproj" />
  </ItemGroup>

</Project>
