services:
  seq:
    image: datalust/seq:latest
    container_name: Viv_Seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_API_KEY=viv_seq_77
    ports:
      - "5341:5341"
    volumes:
      - seq_data:/data
    networks:
      - viv-net
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: Viv_Redis
    command: redis-server --requirepass viv_redis_77
    ports:
      - "6379:6379"
    networks:
      - viv-net
    restart: unless-stopped

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: Viv_SQLServer
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=viv_sqlserver_77
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - viv-net
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: Viv_RabbitMQ
    environment:
      - RABBITMQ_DEFAULT_USER=viv
      - RABBITMQ_DEFAULT_PASS=viv_rabbitmq_77
      - RABBITMQ_DEFAULT_VHOST=/viv
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - viv-net
    restart: unless-stopped

  caddy:
    image: caddy:latest
    container_name: Viv-Caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - viv-net
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

name: viv

networks:
  viv-net:
    driver: bridge

volumes:
  seq_data:
  sqlserver_data:
  caddy_data:
  caddy_config:
