services:
  seq:
    image: datalust/seq:latest
    container_name: Viv_Seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_API_KEY=viv_seq_77
    ports:
      - "5341:5341"
    volumes:
      - seq_data:/data
    networks:
      - viv-net
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: Viv_Redis
    command: redis-server --requirepass viv_redis_77
    ports:
      - "6379:6379"
    networks:
      - viv-net
    restart: unless-stopped

  postgresql:
    image: postgres:latest
    container_name: Viv_PostgreSql
    environment:
      POSTGRES_PASSWORD: viv_pgsql_77
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - viv-net
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: Viv_pgAdmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=viv@test.com
      - PGADMIN_DEFAULT_PASSWORD=viv_pgadmin_77
    ports:
      - "5050:80"
    networks:
      - viv-net
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: Viv_RabbitMQ
    environment:
      - RABBITMQ_DEFAULT_USER=viv
      - RABBITMQ_DEFAULT_PASS=viv_rabbitmq_77
      - RABBITMQ_DEFAULT_VHOST=/viv
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - viv-net
    restart: unless-stopped
   
  caddy:
    image: caddy:latest
    container_name: Viv-Caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - viv-net
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

name: viv

networks:
  viv-net:
    driver: bridge

volumes:
  seq_data:
  caddy_data:
  caddy_config: