<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Entity\Dto\" />
    <Folder Include="IService\" />
    <Folder Include="Service\" />
    <Folder Include="IRepository\" />
    <Folder Include="Repository\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Viv.Entity\Viv.Entity.csproj" />
  </ItemGroup>

</Project>
