namespace Viv.Momo.Sync
{
    public enum DiffType
    {
        Added,
        Modified,
        Deleted
    }

    public class ColumnInfo
    {
        public string Name { get; set; } = string.Empty;
        public Type ClrType { get; set; } = null!;
        public string SqlType { get; set; } = string.Empty;
        public int? MaxLength { get; set; }
        public bool IsNullable { get; set; }
        public bool IsPrimaryKey { get; set; }
        public bool IsAutoGenerated { get; set; }
        public string? DefaultValue { get; set; }

        public string FullSqlType
        {
            get
            {
                var type = SqlType;
                if (MaxLength.HasValue && (SqlType.Contains("varchar", StringComparison.OrdinalIgnoreCase) || SqlType.Contains("char", StringComparison.OrdinalIgnoreCase)))
                    type = SqlType.Replace("(max)", $"({MaxLength})");
                return type;
            }
        }
    }

    public class TableInfo
    {
        public string Name { get; set; } = string.Empty;
        public List<ColumnInfo> Columns { get; set; } = [];
    }

    public class ColumnDiff
    {
        public string TableName { get; set; } = string.Empty;
        public string ColumnName { get; set; } = string.Empty;
        public DiffType Type { get; set; }
        public ColumnInfo? Expected { get; set; }
        public ColumnInfo? Actual { get; set; }
    }

    public class TableDiff
    {
        public string TableName { get; set; } = string.Empty;
        public DiffType Type { get; set; }
        public List<ColumnDiff> ColumnDiffs { get; set; } = [];
    }

    public class SyncDiffResult
    {
        public List<TableDiff> NewTables { get; set; } = [];
        public List<TableDiff> DeletedTables { get; set; } = [];
        public List<TableDiff> ModifiedTables { get; set; } = [];

        public bool HasChanges => NewTables.Count > 0 || DeletedTables.Count > 0 || ModifiedTables.Count > 0;

        public int TotalChangeCount => NewTables.Count + DeletedTables.Count + ModifiedTables.Sum(t => t.ColumnDiffs.Count);
    }
}
