<Project Sdk="Aspire.AppHost.Sdk/13.4.5">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>4aebb5cf-c4bf-438d-823d-2bffac23f28b</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Redis" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Viv.Apex.Api\Viv.Apex.Api.csproj" />
    <ProjectReference Include="..\..\Viv.Apex.Worker\Viv.Apex.Worker.csproj" />
    <ProjectReference Include="..\..\Viv.DeepRed.Api\Viv.DeepRed.Api.csproj" />
    <ProjectReference Include="..\..\Viv.DeepRed.Worker\Viv.DeepRed.Worker.csproj" />
    <ProjectReference Include="..\..\Viv.Herta.Api\Viv.Herta.Api.csproj" />
    <ProjectReference Include="..\..\Viv.Herta.Link\Viv.Herta.Link.csproj" />
    <ProjectReference Include="..\..\Viv.SakuMai.Api\Viv.SakuMai.Api.csproj" />
    <ProjectReference Include="..\Viv.Aspire.Gateway\Viv.Aspire.Gateway.csproj" />
  </ItemGroup>

</Project>
