<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.3" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
    <PackageReference Include="TickerQ" Version="10.3.0" />
    <PackageReference Include="TickerQ.Dashboard" Version="10.3.0" />
    <PackageReference Include="TickerQ.EntityFrameworkCore" Version="10.3.0" />
    <PackageReference Include="TickerQ.Utilities" Version="10.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Viv.Contracts\Viv.Contracts.csproj" />
    <ProjectReference Include="..\Viv.Momo\Viv.Momo.csproj" />
    <ProjectReference Include="..\Viv.Vva\Viv.Vva.csproj" />
  </ItemGroup>

</Project>
